let data = [
  {
     id:1,
    image: "/images/menshirt.jpg",
    title: "Men's Regular Shirt",
    type:"shirt",
    price: 200,
    totalquantity: 5,
    rating: "4.0",
  },
  { 
    id:2,
    image: "/images/mensshirt1.jpg",
    title: "Mens's regular Shirt",
    type:"shirt",
    price: 500,
    totalquantity: 25,
    rating: "4.0",
  },
  {
    id:3,
    image: "/images/menshirt2.jpg",
    title: "Mens's regular Shirt",
    type:"shirt",
    price: 700,
    totalquantity: 30,
    rating: "4.0",
  },
  { 
    id:4,
    image: "/images/menshirt3.jpg",
    title: "Mens's regular Shirt",
    type:"shirt",
    price: 1000,
    totalquantity:50,
    rating: "4.0",
  },
  { 
    id:5,
    image: "/images/menshirt4.jpg",
    title: "Mens's regular Shirt",
    type:"shirt",
    price: 1100,
    totalquantity: 60,
    rating: "4.0",
  },
  {
     id:6,
    image: "/images/menshirt5.jpg",
    title: "Mens's regular Shirt",
    type:"shirt",
    price: 1200,
    totalquantity: 48,
    rating: "4.0",
  },
  {
    id:7,
    image: "/images/menpant1.jpg",
    title: "Mens's regular Pant's",
    type:"pant",
    price: 500,
    totalquantity: 48,
    rating: "4.0",
  },
  {
    id:8,
    image: "/images/menpant2.jpg",
    title: "Mens's regular Pant's",
    type:"pant",
    price: 600,
    totalquantity:50,
    rating: "4.0",
  },
  {
    id:9,
    image: "/images/menpant3.jpg",
    title: "Mens's regular Pant's",
    type:"pant",
    price: 700,
    totalquantity: 58,
    rating: "4.0",
  },
  {
    id:10,
    image: "/images/menpant4.jpg",
    title: "Mens's regular Pant's",
    type:"pant",
    price: 800,
    totalquantity: 70,
    rating: "4.0",
  },
  {
    id:11,
    image: "/images/menpant5.jpg",
    title: "Mens's regular Pant's",
    type:"pant",
    price: 800,
    totalquantity: 80,
    rating: "4.0",
  },
];
export default data;
